### ISSUE TITLE
Podman binary not found results in a panic

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-engine-deployer-podman#7]
### Discussed in https://github.com/orgs/arcalot/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **lmilbaum** March  3, 2023</sup>
I use MacOS box.
Created config.yaml file:
```
deployer:
  type: docker
```

Run the command:
`./arcaflow -input input.yaml -config ./config.yaml`

Output:
```
panic: podman binary not found in $PATH, please provide it in configuration

goroutine 1 [running]:
go.flow.arcalot.io/podmandeployer.podmanGetDefaultPath(...)
        /Users/lmilbaum/go/pkg/mod/go.flow.arcalot.io/podmandeployer@v0.2.0/schema.go:18
go.flow.arcalot.io/podmandeployer.init()
        /Users/lmilbaum/go/pkg/mod/go.flow.arcalot.io/podmandeployer@v0.2.0/schema.go:68 +0x3dcc
```</div>

**Comment by jaredoconnell** [comment]
Useful info:
https://github.com/arcalot/arcaflow-engine-deployer-podman/blob/main/factory.go#L30
It should also check its parameters.

**Comment by jdowni000** [comment]
I have opened a PR #8 to address this. I have some feedback to address but will continue to work through this.

**Comment by jdowni000** [comment]
PR #8 has been merged.
